apiVersion: v1
kind: Service
metadata:
  name: summarizer
  namespace: summarizer
  labels:
    app.kubernetes.io/name: summarizer
    app.kubernetes.io/part-of: user-adaptive-summarization
  annotations:
    lbipam.cilium.io/ips: 192.168.2.203
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: summarizer
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
