apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:D3Qw/kKpoWA5rqAdlCnx4ynAkfIMOSluAPZeJHqYD0jkasKvx6ozB6gsbQHAj1RMtGHPYkhSaiS48HGxlx9WMsmE1/D+n5RAaKJ9IesD2TdcQ0dGMB4/gyXcPPNjAAF/CPdLwzMj2msP8MZ81ei6CnRLVJbHE/G8niAVuOQxPieyPpyQ1MKDJEXHfr2eQqg9X63i4RyNOUU5u9ScLNNdNDCl+iJOAGsC7CA8U9js4ZqGkd9r2BHVXFx+x/0Y926rxQTOVhNsyygTvwR7uZZ/j3pO41wbO1d1V62bCsGbTlXL29fS,iv:stbEhI5P3Ccz0z7/qBR0yHMG4hpw8EfjWoYyI9sIbM0=,tag:O2y5J7tS9Am9OCvfxBX+Bg==,type:str]
kind: Secret
metadata:
    name: hermes-ghcr-pull
    namespace: agents
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1qu6zhplyqa66qs6c9zcvjpqrkm7amcwp3sp5sya707f80rvjecmqean5y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0c0ZtUHNKTUdtdUtJVkI5
            OVFlbXdrMXhJM1RmbEUwWEtFVnUybGYxUEZrCnNuOWV2QlFzeFovb3BneEFrMzJK
            VTdOV05obldZbE5BeHZKNWtaL0cwaVEKLS0tIEpiQXJ4cXR3bUp2UGtFZ2pYd240
            anBoU1JKRU5hQmNBM2hXdXpEZkswbDQKTR9NZvW+j5XhEPk5VN4COEEB4yFLhLMk
            Fqk/fjI1NyJNlGZS+KquhwZzZm0TbxWml0SILptA0PWzzGF20vmz6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T01:48:36Z"
    mac: ENC[AES256_GCM,data:iZMN13ru1sg+Xv8/Zkn088OeV+/TaMezhOUzi5igrU3oxy99EiCSST3mkj1CZrEuyyIL+7V5aSWYPwQgTlPbI64goVTX63fRPF2kMKFKxUiUK8izj/69Za2ClyJU4M9XkwrgbUNEGL2p2ey6WCXu7YKd6M5sKGcOKWScM/zyPCs=,iv:WPdl7Q+uaJ90ToCGj4CG9/jie7M1es4SdG+aFT87S2M=,tag:exkfb+Jiy1YCGAkaizb7yQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
