apiVersion: v1
kind: Secret
metadata:
    name: apollo-runtime
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:b1WlkB+e18Lnp11NCgc/FqROmQE/P1BqdvqvXdbzTd5fbm/3+ZoGpGuGASxHj70W3B+SQZFhtS3z17DyBJ16l2P79N3i80C9GSjzM7AKnuL1Uki+BwERNRfmxsvMBU/orZsQ+f0kFQPbFf97gHR53aUqUg==,iv:KprbWyIn5vDTgYra86BeRnXrCp26gK2RYJvebEXvNy4=,tag:7cuodvCSAIfjFq+FVuf1iw==,type:str]
    session-cookie-secret: ENC[AES256_GCM,data:wm3tyfuOBkt0MrD9jAjVmYmKzzHMvunaxeaQRNLlcAtueJgM+i90teG0FOIYXOUaufieGe7t7P5O4AbkZfNfOw==,iv:p0S03vX8WhbGTFnJ+W4BsSjOUw3gqZ/DFSzUp0CNeLg=,tag:KT1i/ERAi2Jdj+cVzGtBaQ==,type:str]
sops:
    age:
        - recipient: age1qu6zhplyqa66qs6c9zcvjpqrkm7amcwp3sp5sya707f80rvjecmqean5y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3N1hjSDFKb0RybGc1MGhs
            OExIS1JRZ2hnejNUMlp0b3FoZk1JNFVzTkUwClhudFhNVXk1d2hhY2lFYndYbW5u
            SzFob0EzZzg3OFBaUWVrMUlXcmJFVDAKLS0tIEdQdGlnNTBXRytIeUI2SXlWb1Qx
            ZzJ1aGI1TzY3VTE3bmcvSW5SRUI2dWcK8Ru8PVd9hXWYQr/N7xANLZNu1kDaX6Y5
            F8Hb3V4MhtIlzxaqzC67TSYwiuihBX8o+tRB8NV8KAKU8cf7I/ohOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T18:14:17Z"
    mac: ENC[AES256_GCM,data:pwf38G5Sl/W3RDYz04cpnCTTTFlmA051sgVej8Z05NQUz9EIAN02OpsTxHahTs2Be7cPvQGO6QxhBWR8XS3jHUN7RaxlqRYlI6qIGz+QBJH0XTORIhkCpEsPI/yj5dLUqowSejxiKDtP9fqj+zEcdM3xfGt8ktDQhyrR9D45XNY=,iv:WsHO6pPEc0K3EtkR2JsBlt2fESMqZOFXT2nx5eaFin8=,tag:iI+RmlZeZ7uyTor37XCQgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
