apiVersion: v1
kind: Service
metadata:
  name: apollo
  labels:
    app.kubernetes.io/name: apollo
spec:
  selector:
    app.kubernetes.io/name: apollo
  ports:
    - name: http
      port: 80
      targetPort: http
