apiVersion: v1
kind: Secret
metadata:
    name: apollo-runtime
type: Opaque
stringData:
    session-cookie-secret: ENC[AES256_GCM,data:I93MQXjTrBa0atsNVZtjKFIgoJiFpXTvc3965Wp0haD6IwC+kCKRAfNtPPg+UKvpJAV+Ly4lU3A5x1wNdHQTRQ==,iv:CCRCOdgkTyd7mEv0+RaA3RpdUmjLd+XQNy2KOay5f8E=,tag:o3mDOzeSCcp7imL/Rbjlxw==,type:str]
sops:
    age:
        - recipient: age1qu6zhplyqa66qs6c9zcvjpqrkm7amcwp3sp5sya707f80rvjecmqean5y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNEk4UnhnS1JXVkdGdGdJ
            ZFpwUzVIOFlRYjFTT3VpcmQzM0VxYVhFa0dvCnQ1R0FXaWhuR1RaeWh1T0xiOGpY
            NDd0Nk9IRklNS1ViQnFkTUhFdEo5SjQKLS0tIDAzSTVjT2lkZTMvR09zYzJFajVP
            R0dxNTVGazVhRklxSFN5bVFzUFZtYXMKhp5hjtQkBjwi6zJ+LHizTr2GEsUt0yBD
            TUI+5htrUFu5/P6SDt54hSl6dE6qj7m1IYvbfgcOLbUeGibyBwlscg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T18:10:10Z"
    mac: ENC[AES256_GCM,data:35tbHVzSn27sGbKJRwOZaAxtxGnGgohA92AS10t15LZ+1jSw1lbA8RfNQe0O6zdzUXtehKubtqAmlt6bSOk6M39lOEuhkQkD38+YfIVw89YuUkRTOfe/67kAjWwSmiaKCCB04Y2FZl/FVXI12GfIXDtHeoSjzmT86LXUCChTqKU=,iv:T6UIHHXpxgKdpL+AY4dzKGdESOnka21YlSUgT96M70U=,tag:21g0mBxx4Hz4T/+GH7qCwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
