apiVersion: v1
kind: Secret
metadata:
    name: athena-edge-runtime
    namespace: athena
type: Opaque
stringData:
    ATHENA_EDGE_HASH_SALT: ENC[AES256_GCM,data:VP4e5hI5atRva2EvmRiaYvdcCXoIfYtmBNPpGpQRkA9yTi5Z6UYX0YghWXaMMFlMGliA7jU2eY3KBDkIo5TU9w==,iv:4oYmsQ9CAn46xxNRYDSDIY4/tOl9Rs62GEEd74CyRLA=,tag:RYOYIX3HxoOqPHH7C7+4uw==,type:str]
    ATHENA_EDGE_TOKENS: ENC[AES256_GCM,data:Sn3rhbjIQMNvaekoyvkuPufnJ32aJV8/VoMXA9OnQYxUTfkWKxynyb2pT/H7d8OTKh0Ep4z4NyU=,iv:RIi7Bd8f4+nXeLVBkMuDogEocyRFN3E1dUNy+4z7YTM=,tag:ZSol0qRSnOwVRMeIZeBDjg==,type:str]
sops:
    age:
        - recipient: age1qu6zhplyqa66qs6c9zcvjpqrkm7amcwp3sp5sya707f80rvjecmqean5y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITWJkNGVsSXZYRXVYWHdV
            bk5tRFNHUjRXbVBWN3dmRS8yT3V3dlhCQ3pBCmZKS2U0U2xlcFBkeDZPNlhycE9P
            L1R4UjA5Q3NpNFdYRERKK1dVaTFsZFEKLS0tIElDMUppZXRERG1nNVl3WG9PaVFu
            b01TK2pScUt4dmpvUUR5YUQ2aHZYazgKHaydQYErqEczG+qYmyi3PQ05+gI+N4v4
            mQXdawllV07sRJ5OOQTcEq2rgXpE4y8VQ84xm0Qi5DZht4tmEpLcfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T22:16:13Z"
    mac: ENC[AES256_GCM,data:V5HhUO41s3XD9nxvatniFH4sggwNEIByiqVd6O1gKUu9ww7bQue4J+Rx/iJkFrNZqTwazALLgeiOvmFepWlze50CnzLJD9nICwLMqHHxLzgN9Crw1jWAQ11uVxw/34pxWL/GB9tT2QFw+aAzlOAtXWcpun6ZhlEoq/F3FmnXFrY=,iv:GQB9ivWWi5pGsxwaP/gPqABazGhfSuFrpvLCkvpDfos=,tag:NKCfBNln7RK6Zuk2GoP6aQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
