apiVersion: v1
kind: Secret
metadata:
    name: athena-edge-tunnel-credentials
    namespace: athena
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:nmUpKFAgg8I1Ma7/7WogNFlnxnYY6/4M0edtm5TVyKe+XkIgBDPwNSXvx0bjBSofNenkRe575UW3UCbx4XEX9tmTzKq/rVJbox3EDWrPzTsgts9RY1Em1Sl9Zt/Y9IVKIRUtxkha6mNmArsAhpeBYe3QJWFYsec0fzPnnivtIecgRYdX8QXtojIsEXKqwl8OKYt+K5ZokRiwv+VFcN9+LjNS6DGNNh/dQD1nNE54eg==,iv:02SpIGunLJemBXItz/gsGRqV/Sjms+y/GjR3efH6qMI=,tag:+nBRGGUkWafWHonKRpbjdQ==,type:str]
sops:
    age:
        - recipient: age1qu6zhplyqa66qs6c9zcvjpqrkm7amcwp3sp5sya707f80rvjecmqean5y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRHdaSHczVVQreUptYTR4
            UVNxVFBoMU0rQVE3MElzQlBSUWdRY3BjWmgwClBGcGZrS2tmZnNnaGFacW94QWNP
            a28wV0hzeGRNRmJyVXI2U0FNRkxGM3cKLS0tIGJhaFF1TEExNkdtd0cvWkhieTZz
            elo4ZytyODdtMkk1NUNPN1V3UU53NDgKUWLyayGA1qLu3piXODRsr6VJyYQoiBNC
            L8VgJH0x/0eA7Xt2rCVOREoBIJXMkmEEmM5g/EuVdPulXv/HzlfEsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T15:12:22Z"
    mac: ENC[AES256_GCM,data:u0cW48rkKcyXpPk095SAwdnLCxctfJubL3sy2SH/v7BNBMJNS0mXRm157kOAIdqsXe4PVk4tq+lAI/CP/kZWEioW4uJ8MIN3afaUTWhftX7MGzsqchPmz7Y62NsEYt1Ha4nwYZMHL+ME9MzicWHGsC5rYH1tITA2PWpaKpEeaz0=,iv:gPFLOprMb1A3mG8jXhTrWPNpsk8bEklRojEmn8C3dJE=,tag:6c7pgymID1reiAh0DoltJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
