apiVersion: v1
kind: Secret
metadata:
    name: athena-edge-runtime
    namespace: athena
type: Opaque
stringData:
    ATHENA_EDGE_HASH_SALT: ENC[AES256_GCM,data:RYbkfDoeNN9bIPC5ImA3qyZ1MR5zIhnASlDn3wj847hiWt1PtcevO/ltu61w0EVy5AMnF7kGLogn1dkHYS6hqg==,iv:NgKno7motK5gVLAXq6/CJJUzwAPxUfe+ydU+FXJOMFk=,tag:RyJdi8v4wXn7wdKFaFzeCg==,type:str]
    ATHENA_EDGE_TOKENS: ENC[AES256_GCM,data:zuBRQP6YMEjFjLgEEeAqrJ9sf7ll8qAjfVgrFmGUlAD3LxF+EB5xzwxGi3SPH7tl5gsYi1UXvmo8rBri/1AuDJyLqo5UkK5qFeotjc1dmKy4T3klSleZZo71F9qQfoURaMWYCFoBFHctW9RuQj2atWxb7ITa+6/cLXvA+4pqLf31/2HtUYp2ErfUJ/ymx97lxO4cay1MbHr/oSsIkNucUyEQPubgnLAZDncd0WN4SCrfcmT+0TU/g9xgxOS3va/uoZ2RtmxG7K1Jy0ECKw8PL19SL5cAldcA5ESX,iv:ZSJxFnMKNlJXXisYAqhBD7a0uaDPiVpge+0/dymIFfs=,tag:wmzF6/54CzMiQ8i02FC67w==,type:str]
    ATHENA_EDGE_POSTGRES_DSN: ENC[AES256_GCM,data:9XjG0FZgXbhUd2xwJ8saSRzAPAuXo2twf+5E7hxdRM3WLq2rAEyEIs6opp7WRJDuliIRslqfO/gMyX78fuPocre6UboveIZqp2H1Vuj1Yn7kKC2AMdbFvML4CVwup867p/bpqzmEdh6zhaU/1zXFJSlHfZ1wwj7S,iv:7TuZcdoApBSZK2h8loXLf3WFcqmMKt4vHX60eBtPExg=,tag:R8sQcDi1sU8wpQVEFUAdNA==,type:str]
sops:
    age:
        - recipient: age1qu6zhplyqa66qs6c9zcvjpqrkm7amcwp3sp5sya707f80rvjecmqean5y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SE9BbEh1Z3VYVUYwRk54
            blcyMXZDdlRpSStmaVl2S0xTRkNRN0FPdVZNCmhYV09NUDdlVFhmUnk2elVVKzJ2
            TlRPeWo2ZXNQejNaTW1veGM2MUQyTzQKLS0tIGdHMG8yb0hWc2gvQmxLcHYrMWZn
            VlpRdmlPTXhHN2tUNWUxZHRkcEJHdGcK3+yN0hr8bWm1bvwBNfAGpAfbE6EPrnOq
            reXNe4c2LsHPH0Rqnqwdfl5VvvG7qmdIEM1pw3lyI/gDY8QEz7kikg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T20:28:45Z"
    mac: ENC[AES256_GCM,data:W1ae6Xb3o/5AbeNH4z1vYPnYti80R8gGpxuiX40S3Ue3l5RPSPSSJbvdml8d4N7wy46zU0BV0FzG/2OiRe56S/FOd1+FwghcV+vElQfrfc0ZxGJnY50fiKaCiNSRIHgQu5ltMhG8s9k8Jo6Q0aJs4EzKRZ9ZddwNjACGyZMk8V4=,iv:hQntUIXyp8dyKDTW9/U+eQxr7EM587RfOkwEuPG5jdY=,tag:eqHQmDyeaTDMalfOMy532g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
