apiVersion: v1
kind: ServiceAccount
metadata:
  name: athena
  namespace: athena
  labels:
    app.kubernetes.io/name: athena
    app.kubernetes.io/part-of: ashton
imagePullSecrets:
  - name: athena-ghcr-pull
