apiVersion: v1
kind: Secret
metadata:
    name: athena-edge-runtime
    namespace: athena
type: Opaque
stringData:
    ATHENA_EDGE_HASH_SALT: ENC[AES256_GCM,data:LCTunKdswC3S9OxRhatcC1MpgMoVZLmWaqu8zAQW1Wf/YwGwiTS9oTBbxk7SxR3LLq1dSAbf70Jex8KQmE+dKg==,iv:TwRhXEmE0zPTmbAmF39o8aX3hkacqNPDYQqgtNrIjPg=,tag:HDRlFace+JATM/I4pxFS5A==,type:str]
    ATHENA_EDGE_TOKENS: ENC[AES256_GCM,data:J82zMZVy6pJQpyfbw1jNZnUGQbZ2nrUpfktkTJSIdYDepofdJSGK2f1XFV1tcd8BykvgEcRuhHWEqv+1xkLt52fPj4ZW7hEWbIgNzinkFg7r2KCh+pZiFm7hV4joPTD9mhGDTGXN6J/qrkNjExGEmsv3QgbTNUsDEmfVsPN2GQCEpgxpwLzbKYCfA/gI/hRFCmK4Wrc0mGGyGHadOZY3Chz3tBaiATfW/B2E72NU0PBvcilv9SQ9ldUNRBgy2PRWJ49MeC+enlcmQ8zn0SPtl4gXemUv3ET0EjK/,iv:AHZj8MUfusHs9yqpr9oKNkgSVdH5PiBee+kXJNJ9ME8=,tag:wXeD1etzRy/w+MQWsdunKw==,type:str]
sops:
    age:
        - recipient: age1qu6zhplyqa66qs6c9zcvjpqrkm7amcwp3sp5sya707f80rvjecmqean5y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAza2FUTUp3dVpJTGZGOXd4
            WmZTVys5dG9VS2tQakoxakJCNzJNaVBSWXhzCk53U2tKNlVCeDZwb0IwWmkrVXBG
            ZXJVVi9PQXpMVW5tZDJWUXQ5WlZsZmMKLS0tIEZXbUFuR1VTSm01djNGUDVvaEo3
            TndBNDFDd0JkQWdpK3I5c1JPUUp3QUEKQuvaVVyXhsyfPZ+heVOelnGgdB8yK+V6
            1lkIO1oqWB081USOendtsZoevDjBDy0zONmZuDjwx/62K1r4u0fJTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T22:04:16Z"
    mac: ENC[AES256_GCM,data:0p9VblcznmQKxraOQS7QC/GpLfXn2mHpgA2jp9gWSykPRBhi664NQCZ4vUHNf6oOaxYXjHq+FAV2kHimkTc2bmmIn7YU4HoXZDrT7mcoK02wGreAiqYVdrVTK9WROlinBy6o6R9T3htlhnb5QsHnE7QpU6SFelRJJ0XouA/ot1o=,iv:L3GO7H9QmWM5ywnl70vT2f/If25aDwC5cafzaWThIP0=,tag:5j0OCltUU8tuFpMLqS242g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
