apiVersion: v1
kind: Secret
metadata:
    name: athena-ghcr-pull
    namespace: athena
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:XUvrvHnnPI8jhmCpZ9/YoMFjO0WJhoh6sK0HgBc3ubfIO5ct69nr3Y/43WVS+Ldu7MNTRI6veBBX3ysHSpE1HUwN6aQWdrbV3YYWfWZhf9ftgBWc9qa9w4VJFTiKGe+9nkjkzApwNasynunZfmOEfnBl4unAYG023QVBRWqDGoKRylhgvAXLV+a9hZC2yhJdl4YS+WaHqHmT0eUPWs1P54a8TzkRuTS2LTeD,iv:Me5E3IXdZv/sd4YcnJVUtitHujKZhlrNC/eMAjuvkcU=,tag:ssem7GnTLNQ5JSQVgpe83w==,type:str]
sops:
    age:
        - recipient: age1qu6zhplyqa66qs6c9zcvjpqrkm7amcwp3sp5sya707f80rvjecmqean5y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TTZZKzBoT0paV3F6YVJD
            Y0xNK1V4cXBBMTRaZmt6TEQrMTVVdlZSMjJzCnlpb0hiMVVLaU9IcUNkN0hMN2dS
            YjJyTVNTU0E5VXNGYUVjSk5mWGlhT2MKLS0tIDBic0VkcFJtbGE0bkRPbjNCS1pV
            RXpaT0VjcHdOVTAwOXUrUjFqMzZhYUEKEaashQM8xq2y/4nq7gxGp+Cf8N4KnV6r
            EIpbwXWM3c0UXwczUhchRWhfIoHvzJFKSDhU6Pv1RlLLbrVxFlxd8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T03:03:02Z"
    mac: ENC[AES256_GCM,data:zp16iOS+rm0HU7ESM4fyNJ9GD4BhAStnJuN7l/n9BhoWsQesfBlTY257AQKetbR1jCTveGqP3Dsphxi4fwllrNx4F9d7Ee+OrJ+4CjaKsW0S7OmGcPncLAZJE7Lw9qnBEwAbFxaFyFX6/7mFHGHcMpOUuvCX+rdHomv6GPJZThs=,iv:dn0JSCPmYxxGBqPqb/S6P4dKuf2OM88p79b+HtrP48c=,tag:38Cid26perZqHpQ1WqpBEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
