apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - athena-serviceaccount.yaml
  - athena-ghcr-pull-secret.yaml
  - athena-deployment.yaml
  - athena-edge-runtime-secret.yaml
  - athena-service.yaml
  - athena-edge-proxy-configmap.yaml
  - athena-edge-proxy-deployment.yaml
  - athena-edge-proxy-service.yaml
  - athena-edge-tunnel-deployment.yaml
