apiVersion: v1
kind: Secret
metadata:
    name: summarizer-proxy-auth
    namespace: summarizer
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:/f54vyKItTKdJNIEwQu77fDp8y0kr9W7XIu9/iGT8qWgQUmNR9BbjhU33m/0N666WjxuwdW9KuhWKY1PXzCk/FPm/Hhhxw==,iv:VVwu2/by5AOqXB2fexegJkFUb9+XaA/0V+AQ+bNNJ3o=,tag:gwU1gc5RkkdlMdFud7ZqBg==,type:str]
sops:
    age:
        - recipient: age1qu6zhplyqa66qs6c9zcvjpqrkm7amcwp3sp5sya707f80rvjecmqean5y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdjBrYnE3VVhPYVBuYXlu
            ZmllaVh5M2tLbUVtZWtTbkhhWFRTTEZOZ1R3CnNjSTJVRUZlMms4Vm1nZFFRNE1k
            WXd5Z0Erd0hXOVpEQUErL3hsTXNaNlUKLS0tIGgxQlhiRjRqM21NTTNOaHFNejBq
            VW9NRnFrWEh1VVFtNGlNbmlRaHhvMjQKwMa9YboiKu/mdY5mVsaSUvcCM0sM7lKm
            sd0941yl8bBSx3jTqYOoIYRXHt6SWq+63oJQLV4BbYtW3xk1BE26Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T06:37:57Z"
    mac: ENC[AES256_GCM,data:7A8lhP6QeJoSynPLJA0ypVQyTTeorWCBgzh44jpAbH8nIBomHQ22zdTO0Wct+UAQ51tpv/UEWU/EnYa1s/iQaIsgPSOV9IkXtiuJ6CCq7WLLZoofoMpxmT82bbSKju/294AVc2qLpdTq5W7UILKQLxufYW8OpslkScmeruD6H0U=,iv:nT5fzNhKov7lqNQ9NWtb6a5JWwrjQefA6y8uw1W5E7U=,tag:6KcREIkXEWbwws6mQvfsxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
