apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
    namespace: agents
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Gi8wm1By3Wpj,iv:PK9RI9u1Is7hkmqG0ygDyqqBXjegKwSwD3fA6LDCXn0=,tag:hx/XFMcjBA5LO8gY9Mknow==,type:str]
    password: ENC[AES256_GCM,data:11wCO/ZdzjmqE2UbNMtSDuAnFLgrbqPmAMrbTGEKmJM=,iv:N1iMK9l37RYp682Sob1Up38w/622d8Vm5Yz0mMpGMRQ=,tag:EE760+H+/rAMxMVvc+MjaA==,type:str]
    database: ENC[AES256_GCM,data:jux6pe7JPwG/,iv:t3/5kOLIVdwnIrnq1+nJheehK+pshAZ/V4Ml1R0QiPc=,tag:zCEV8Io19yPHxR4GDS0/ug==,type:str]
sops:
    age:
        - recipient: age1qu6zhplyqa66qs6c9zcvjpqrkm7amcwp3sp5sya707f80rvjecmqean5y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZjRneVI5bEdJNjJ2MW1S
            SnhWa1piR1ByNnRJVS90dzNkbzBRaGV3ejFjCjNNbDRRSkI5enRKWDQ0YkFzMU9E
            eDlXWEkzbk5ublhHcnpFMFdWT3dLcVUKLS0tIHdEa0FDN3dENnVPS3dkR3lueVo3
            UTF4cHdOR0s0Q3A2dUZMbFJEbnQyYWsKPe7UvXm1jH0Qo3z0vFTOOLo1wdJgv58g
            aevkC1xJhyX/yknkfeTdfJnScOZWbIUscii6mXi6Iu1KEV9YwAUC3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T17:58:25Z"
    mac: ENC[AES256_GCM,data:dqO1zRHC87G/qmo524Hsu8OpR/ozMgK91eG7+y+GnLD5hRH50MNnU2er7KYP4+BMcLLVbQAdvKPWF+AEuFfaTwDWtJ7Web/9Kj4K+Xt9zwHbsHdcOIFyDTWTv4nInHXgLweQHjTJ+bU+YVsDyIZGs7HoIG1K7XoMc30uDSFpg/Y=,iv:METy3RvJydBWtvRPDsV44sNGnr+7DTqzdx77IWXopJY=,tag:Y2sBOI9x3JftHkinfPDPUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
