apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-cache
  namespace: ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: local-path
