apiVersion: v1
kind: Service
metadata:
  name: vllm
  namespace: ai
  labels:
    app.kubernetes.io/name: vllm
    app.kubernetes.io/part-of: prometheus-ai
  annotations:
    lbipam.cilium.io/ips: 192.168.50.205
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: vllm
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
