apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-gemma4-cache
  namespace: ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: llama-gemma4-static
  volumeName: llama-gemma4-cache-pv
