apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - langgraph-archive-pv.yaml
  - langgraph-archive-pvc.yaml
  - langgraph-configmap.yaml
  - langgraph-deployment.yaml
  - langgraph-service.yaml
