apiVersion: v1
kind: Secret
metadata:
    name: langgraph-runtime
    namespace: agents
type: Opaque
stringData:
    DATABASE_URI: ENC[AES256_GCM,data:61VKrYgTMSIpJLzSycf4awIGEMJdp3GybsDbSwiJnbRx4eY9bEy1G7eL4bWw/yDra0M7c9XkDHfzXFumO2Ud0bI5mQI5xY9BJXLhjRjLXPKY+otRHCrmKy1gFTkajwGC6CTlYP1cSyM=,iv:aA4SJa6+8xy3ptl7Ph4fkYtYl8taMODx03SggcLHccg=,tag:i5r0ElHoYkGCLLBVrjcrjA==,type:str]
    REDIS_URI: ENC[AES256_GCM,data:I9qPNl6bDgNyD5DmzTxQ5mBMTAYbkxtIs9crlqX4RhV2kadFQSY1ATURSUEI,iv:c5vnfce3aUb++FqYeXSkN7TMPAH/spW2uT86fs95QkE=,tag:I2CKQjNYTzWklGKPJA+now==,type:str]
    LANGSMITH_API_KEY: ENC[AES256_GCM,data:H3N6yyjJuqEuyHIJIjNLWrVIVK2dnvaxsB40QoJr8Q==,iv:88s9QSDYR3TKsmWdeNYkt7q3qsdIe7o/PNk+5jIobTk=,tag:kk4amk+BP9ww9ByP7kBtWA==,type:str]
    LANGGRAPH_CLOUD_LICENSE_KEY: ENC[AES256_GCM,data:sQEHBvQuWujw8aHLpXOnL6wEYycZFhU1zrGwTi5laQ==,iv:XCjRd5vJ6n4LjoEk5CQDUXfc/TahiaCw0PR3DgOls6Q=,tag:3iX+vrkdcFWM7+C/kdPIIQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:RTMRuS+lYZPBmi1MiNMVMh1c,iv:of6hqTx6nw065EuZdGm8Y0rXhHXqdcHiAr2oC21OvTs=,tag:PQ/8d8CWnJWXYppWifU+pA==,type:str]
sops:
    age:
        - recipient: age1qu6zhplyqa66qs6c9zcvjpqrkm7amcwp3sp5sya707f80rvjecmqean5y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVUJaNnRYTldmeTJHL1JI
            Q3oyK0hJVis4VFdid2RXZ3dpVHM4OHlIR1c0CnJ5eGJvZjJvR1pWOXJyU2FhYmlW
            ZHFEZkJML2kvdHVHbDJDTWZHU3dtRVUKLS0tIGQyQndvREJyMHBnSUJ5ZHFXTVVZ
            Rml6Nm8wSHhha1FESGV5RFNTMDFXZXMKPsAJUGVsqyratAE+jKzosi3dDe0xLDnt
            L7fLVVLf6yyOhhwqIM/VhlLwTFIL9mTVSEy/diGD8VWj+K7PxMFbVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T17:59:54Z"
    mac: ENC[AES256_GCM,data:8F8tBq9GJ3jxb6Og45Qe2HBdiCLGqO4F4tJWBVKU/v86OWw3cSOjZUYA2ut4aNEAyJWEZew4AQEfj31H8QIKHh58koGeeBXF4c0vi7Z5P74Zg57mQxj2quJhNBiNRg99+n4tM5yeNerMWQVWdTFZb55EDGgRreknxZg06ipvRKI=,iv:zL4Ml03amPuI8OpmlPxQwhsBgo0gnnemhaLxqGEDSpg=,tag:yep8XKi7nBUQihoXPWTGlQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
