apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-helm-controller
  namespace: observability
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchLabels:
      app.kubernetes.io/name: helm-controller
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-kustomize-controller
  namespace: observability
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchLabels:
      app.kubernetes.io/name: kustomize-controller
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-source-controller
  namespace: observability
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchLabels:
      app.kubernetes.io/name: source-controller
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-notification-controller
  namespace: observability
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchLabels:
      app.kubernetes.io/name: notification-controller
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
