apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:Gr4lM/U=,iv:AdHy46RHbK8d3KEq6kzowTxq1VhHLuGw08XP/NW7GkQ=,tag:CN3KWGxZzn10F7Kem1sTWg==,type:str]
    admin-password: ENC[AES256_GCM,data:HUZCt39IJ9633U7j33qP2svw0B2Y2OmOPkl9NMcAmn8=,iv:vbkjxUPJWE5770Nj9eu//353FZgMOA8ZeUUEnFPUGXU=,tag:iVqAundQrDCBkYXem0pdBw==,type:str]
sops:
    age:
        - recipient: age1qu6zhplyqa66qs6c9zcvjpqrkm7amcwp3sp5sya707f80rvjecmqean5y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZFBTL2d2c2x5S2dnQTZu
            aGFLM2RYUnBRQXZIOU9lZlk2UFprbEpLV244Ck8xdmJBN0JpZGlqMjFCNnpEaWQz
            VFpsYjgrN2xJWDhRVmdXQXBWUnk1YUkKLS0tIFNpaUtlbDEvUnV1N3h4OTFLQXNR
            WmN4aVRrRDRzbWRLSG5VMklPakdmSTAKU/+tJDlBzR7zfi2RD42D6NBKdJu1aoMj
            CIegon1zMxASRFKKMHOHFbwpcOP8sZhdKWwxSrgl+yoZfRqk0blBTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T01:04:18Z"
    mac: ENC[AES256_GCM,data:NShzitjxyezkBLszNBDq03vZKlQp/A1fG23P3LKjOWQ/aZ3zjzQRbQnql5UJxAWWIiNIrmv3F+F8qk10kLBNQYk97mINkHRtc9hNgcgrFFDXWG+PjTJNfaOTLmd1QHAHCnpJzLZB81UeKAR8FGedYWYJOf7baIfds/uzR40npyo=,iv:c0CsesUEcTa9j+aU/0kcHJ8oTOOYX7XT0pX7mDiQvXc=,tag:pOJp6yVt7MztspqC6RwjzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
