apiVersion: v1
kind: Secret
metadata:
    name: grafana-athena-postgres-datasource
    namespace: observability
    labels:
        grafana_datasource: "1"
type: Opaque
stringData:
    datasource.yaml: ENC[AES256_GCM,data:VbM+lmDdv+xCaMFB1kT6qIJJmxwkHYX835WczxA3xPBOnUtf2bTMOvSiE0GK1o02NbH79GL84cwMYFuC6QG4ftBNaNyymqK8PZy7TVAvzUPTpUIbVpLwrymOvykPKrgxJjzRPhQsDK1eApWDKErXxrDQjYkWP8UzwAkWHWhCSQT/m8TCDLgh/q9zNQ39pTmBYD7Ul2BSEF22lj3sAgyGEOAENPl5vTdHpm0/7yg0p2dzQg2fvsBf4SwgUfGkxBBQDvYXvw3lHMutvrwFtmLG7CrvjfI6l2NZziVFL9oZtzEHsKMIpOInTuGik9PewopShEECOH7vOrtL/WuA+sEq9Clf2TT5j/d+rBxeA640tqZAKC0mivH579CBAEduG9BCxgUsr7/3JMzzALOOHCKj9nZsqw09ja3HQUNLeaS7Nk/gNe4RDwTQmGsUuPkI7jSAmAEsj4ps7HBDKTQ1TBklKXUkV7KKKLUsbH91fsjDKnZsZLiV2ruOYRutvRfxs2ZE08vg7GTCFK09uFCTiWMXpfBNw73TSeYW7XBDjzpTsDwv8qXBMFEQZs6RZj6cAHOxXmt8RbCkBS/C2mi3zP0SpYRHPiBDT/Yo40UvLluc7YcyXD7l/CxTdIs=,iv:BiPisKMx4vgPBKNBkRsGS4CMvlrrSCshNz02idxURAo=,tag:+p95Hty/vD8k5WzbvB6zww==,type:str]
sops:
    age:
        - recipient: age1qu6zhplyqa66qs6c9zcvjpqrkm7amcwp3sp5sya707f80rvjecmqean5y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZHliNitWcmlkV2VxNVlL
            dE10NE1qSGlDd2RPbnpzbE8xRSttVXE3SUYwCjAwUFA3bm1JZ0RYRmhDeEJKbVNt
            dkZqcjl5VTRJUVdVWVNTaDNURm80UjAKLS0tIEZ4dWlSWEFmbFdhcGtBTkhxOEFH
            RlJlUG1SNUJ1ZUdLT2V3R1ZaRUlZWmsKeKsGtJH0sntvblatrPfR9XgwHJhMk9rY
            ZU1G8Y7quUzqpRhF0WS9a8C8oxkZlK3OYcQpWA5d6wQZD3x6T4O48w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T18:41:25Z"
    mac: ENC[AES256_GCM,data:xs2KaZ9drLqabXkWuJPime9Ymxy66Hbw2y6NinSLrU0EU6wFk0GE3vBRRMKGp6BSOupX5/PvUudg3eVfmyuvm0Jr9OUhMeZz9It8UYrbrPU6b3Tn5JmUahdmlAaS+ednPocIG6GHNsVEQERZxySfal6lzDURBXkpu9a6v4+muj0=,iv:NFWbGDmYa6Bzh+D8vfglXesz4coRLPv7l9qxm0t+ORw=,tag:W4c2Mgmz3P0TU+h3EgpsjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
