apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 30m
  releaseName: kube-prometheus-stack
  targetNamespace: observability
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 82.15.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: observability
      interval: 12h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    crds:
      enabled: true
    grafana:
      defaultDashboardsTimezone: browser
      initChownData:
        enabled: false
      admin:
        existingSecret: grafana-admin
        userKey: admin-user
        passwordKey: admin-password
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.50.202
      persistence:
        enabled: true
        type: sts
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        size: 5Gi
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          searchNamespace: ALL
        datasources:
          enabled: true
          defaultDatasourceEnabled: true
          isDefaultDatasource: true
          uid: prometheus
    kubeProxy:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeControllerManager:
      enabled: false
    prometheus:
      prometheusSpec:
        retention: 3d
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        podMonitorSelector: {}
        podMonitorNamespaceSelector: {}
        probeSelector: {}
        probeNamespaceSelector: {}
        ruleSelector: {}
        ruleNamespaceSelector: {}
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
    alertmanager:
      enabled: true
      alertmanagerSpec:
        retention: 24h
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 2Gi
