apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prometheus-community-helmrepository.yaml
  - metrics-server-helmrepository.yaml
  - gpu-helm-charts-helmrepository.yaml
  - grafana-admin-secret.yaml
  - kube-prometheus-stack-helmrelease.yaml
  - metrics-server-helmrelease.yaml
  - dcgm-exporter-helmrelease.yaml
