apiVersion: v1
kind: Secret
metadata:
    name: postgres-exporter-auth
    namespace: agents
type: Opaque
stringData:
    data_source_name: ENC[AES256_GCM,data:VyFC41g/Jwsma92C7uPosRpkTLchiTxA//+lkZkXYXj6TmLJUWFIrtIuVL0WsecX7Szkd2HLm37jz8QlXZyKKhshunug9x+9QxBFgQub6qvvJ04OA+yG7lgzmzsPcUC7Uu3hHzn97AmpfTyuNyqrBf4aKR6ysk1w,iv:dkXSqlu1aMYCQBcX4gSM8J+90jsmtKxY4VJ+5/FzpOQ=,tag:V5q59d4ecrsbJ0OkAEi1GQ==,type:str]
sops:
    age:
        - recipient: age1qu6zhplyqa66qs6c9zcvjpqrkm7amcwp3sp5sya707f80rvjecmqean5y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SzcwdzJNaEM3RXJlZFEr
            MVpuZGc5cDZZKzRPemJRMiswQWFiRGw3TW5RCkdaMGp2eXY4NitCdUdtemN3ZVVZ
            Wmllb1pIcU5uR3phVmxlT3U3ZytqU3cKLS0tIHpSMjB5ZVN5bk9wT1dDYzJRei8v
            Z1lMK0d1T01PdW1MckhOeTVWTHhlYUkKK0Z42ugXslIZdyiW2ybM+grycSyRbKM7
            zloik37doLxVqec+8ZgNR+WUWtOcKnj4w6KrCs+1xAwz/oAHgmL2bQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T01:09:24Z"
    mac: ENC[AES256_GCM,data:ad4pd4nvUVDqaK2pBaOnH5fXQjeo4wz1Xu501cLCOQ+xB6ZTxOmMq5Ns+P1vtbXCKzcB3dxxTcby35GanWSLoCPe5vLmbt9ZghOiI37+seVOAyl0o26n/8hAhibVDeG9Dj/QGhlddI5UxU6o9TWxM/4Si+gF1UBpB2ThzM5tOmA=,iv:/HXZp3Ifdvb/KlsvKoUjoh1c5DZhv67kkBDULYifaW0=,tag:u+VIlcPak6Yl55p7z3fXZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
