apiVersion: v1
kind: Secret
metadata:
    name: postgres-exporter-auth
    namespace: agents
type: Opaque
stringData:
    data_source_name: ENC[AES256_GCM,data:jrP/KTuYqqfpKtK/3KW7BpZiJtQ6MfSzRfwTcHSt/H6zdaAxpR8CwsnmI8lzHbCwe43nWKH+ggeeHoksKbQcMAmW5hBlXPoKWAgPqDpIu6S3IwgViHXPTBExe7mleKLTVxf9rUCSzBuTec7qMyFxMQBlGQkg1vL7F5k=,iv:IwVRWx4MgZy4Derub7xjp4NNiTc+hWMDQpZwXhdFbvI=,tag:5DUkOP/hfkfnsJ7fmvKtWw==,type:str]
sops:
    age:
        - recipient: age1qu6zhplyqa66qs6c9zcvjpqrkm7amcwp3sp5sya707f80rvjecmqean5y3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdlg4THFaVWtkQ2xqTHlZ
            OHJZUG5KeURuOEtwMHZ3bEhiYzJCdFRUbUFBCk96RFRld1FRUStsc1RuU3hZYy9u
            bDNJNEZGNWp4Vlp4V1ZtL0RmSkRvQjQKLS0tIGRlc1UxeFJoZnM2SjFyeUl0bGxz
            WU9PS0ovWDJ3dVMzYlFxbnAwRURaejQK8wmP45r6lushCxxrqvJH1QW36xZkmvVZ
            qbf8bZfLeJ0EwIZlescz2Xm1ArS7e5i8pt1OmH03eTClkodLoGhF6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T01:16:17Z"
    mac: ENC[AES256_GCM,data:l8Ya/9eqqUAKd4KV3qK58r0LEsARkbDo+zO/4ZMO0G0s5MG+SVONVnpCXXSR1FBdBLfpG+Bv2Zqrq9vwr48+zpR0hQ5dIuhJ/SilgDd9jCPPE6ZMjg5cfYLvAxM9ewxsXlEMwAwgDTnxt0L6INVFfM5Ct+qY4dj9YKLO0tmNo5I=,iv:cma9XxpdjS9Enj24dJvj6kEhPZdNc51q8p6sJnZMg9M=,tag:p2besq/gzf0ZkQeEYInVtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
